services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile.prod
    volumes: []
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "8080:4321"
