services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile.prod # Use the production Dockerfile
    volumes: [] # Disable volume mapping for production
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "8080:4321" # Map host port 8080 to container port 4321
