---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
# k8s doit trouver une instance de stockage qui répond aux exigences
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # Trouver une instance de stockage qui a 2g
      storage: 2Gi
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: postgres
  template:
    metadata:
      labels:
        component: postgres
    spec:
      # Spécifie le volume utilisé pour stocker la donnée
      volumes:
        - name: postgres-storage
          # Spécifie que l'on va utiliser un volume PVC
          persistentVolumeClaim:
            # Correspond au nom spécifié dans le fichier database-persistent-volume-claim
            claimName: database-persistent-volume-claim
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          # Indique dans quel dossier du container la donnée doit être stockée
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/Data
          # Variables d'environnements
          env:
            - name: POSTGRES_PASSWORD
              # Indique que l'on souhaite récupérer la valeur PGPASSWORD du Secret appelé pgpassword
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: postgres
  ports:
    - port: 5432
      targetPort: 5432
--- 