FROM node:16-alpine
WORKDIR '/app'
COPY package.json .
ARG REACT_APP_API_ENTRYPOINT=/api
RUN npm install
COPY . .
# Build le projet
RUN npm run build

# Utilise l'image de base nginx
FROM nginx
EXPOSE 3000
# Copie le fichier de configuration que nous allons créer dans le container
COPY docker/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf
# Copie les fichiers de build dans le dossier du container
COPY --from=0 /app/build /usr/share/nginx/html
